services:
  api-service:
    build: ./api-service
    image: ${REGISTRY}/api-service:${TAG}
    ports: ["8081:8080"]
    networks: [infraflow-net]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/get"]
      interval: 10s
      timeout: 5s
      retries: 3

  web-service:
    build: ./web-service
    image: ${REGISTRY}/web-service:${TAG}
    ports: ["8080:8080"]
    volumes: ["./web-service/nginx.conf:/etc/nginx/nginx.conf:ro"]
    networks: [infraflow-net]
    depends_on:
      api-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  infraflow-net:
    driver: bridge