apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: infraflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: web
        image: ghcr.io/kratos404404/web-service:latest  # le pipeline va mettre le bon tag
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"       # possibilité de mettre des limites plus strictes si on veut forcer l'optimisation,
            memory: "128Mi"  #  ou plus laxistes si les images sont lourdes ou si la machine est lente
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-config
