apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: infraflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: api
        image: ghcr.io/kratos404404/api-service:latest  # le pipeline va mettre le bon tag
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"     # possibilité de mettre des limites plus strictes si on veut forcer l'optimisation,
            memory: "128Mi" #  ou plus laxistes si les images sont lourdes ou si la machine est lente
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /get
            port: 80
        readinessProbe:
          httpGet:
            path: /get
            port: 80
